AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 6 alerting"

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: lab631-su-jmd-deb
      LaunchTemplateData:
        KeyName: lab6-su-jmd
        SecurityGroupIds:
          - !GetAtt InstanceSecurityGroup.GroupId
        ImageId: "ami-007a4d852ac16f59e"
        InstanceType: m4.large
        #t2.small
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: lab631-su-jmd
      MinSize: "1"
      MaxSize: "10"
      DesiredCapacity: "1"
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: "1"
      VPCZoneIdentifier:
        - "subnet-0017c4a5e72ed567f"
        - "subnet-06e941239860097ef"
    UpdatePolicy:
      AutoScalingRollingUpdate:
        MinInstancesInService: '0'
        MaxBatchSize: '1'
        PauseTime: PT12M5S
        WaitOnResourceSignals: true
        SuspendProcesses:
          - HealthCheck
          - ReplaceUnhealthy
          - AZRebalance
          - AlarmNotification
          - ScheduledActions

  ScalingPolicy: 
    Type: AWS::AutoScaling::ScalingPolicy
    Properties: 
      AdjustmentType: "ChangeInCapacity"
      PolicyType: "SimpleScaling"
      Cooldown: "300"
      AutoScalingGroupName: 
        Ref: "AutoScalingGroup"
      ScalingAdjustment: 1

  ScalingPolicyNegative: 
    Type: AWS::AutoScaling::ScalingPolicy
    Properties: 
      AdjustmentType: "ChangeInCapacity"
      PolicyType: "SimpleScaling"
      Cooldown: "300"
      AutoScalingGroupName: 
        Ref: "AutoScalingGroup"
      ScalingAdjustment: -1

  CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: "CPUUtilization"
      Namespace: "AWS/EC2"
      Statistic: "Average"
      Period: 60
      EvaluationPeriods: 2
      Threshold: 60
      AlarmActions: 
        - !Ref ScalingPolicy
      Dimensions:
      - Name: "AutoScalingGroupName"
        Value: !Ref AutoScalingGroup
      ComparisonOperator: "GreaterThanThreshold"

  CPUAlarmNegative:
    Type: AWS::CloudWatch::Alarm
    Properties:
      MetricName: "CPUUtilization"
      Namespace: "AWS/EC2"
      Statistic: "Average"
      Period: 60
      EvaluationPeriods: 2
      Threshold: 40
      AlarmActions: 
        - !Ref ScalingPolicyNegative
      Dimensions:
      - Name: "AutoScalingGroupName"
        Value: !Ref AutoScalingGroup
      ComparisonOperator: "LessThanThreshold"

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow ping and ssh
        VpcId: "vpc-0610446fafca4df10"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  Bastion: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-007a4d852ac16f59e"
      InstanceType: "t2.micro"
      KeyName: "lab6-su-jmd"
      SubnetId: "subnet-0017c4a5e72ed567f"
      SecurityGroupIds: [ !Ref InstanceSecurityGroup ]
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Bastion
