AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 6"

Resources:
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-0149237d81c73e609"
      InstanceType: "t2.micro"
      KeyName: "lab6-su-jmd"
      SubnetId: "subnet-0017c4a5e72ed567f"
      SecurityGroupIds: [ !Ref InstanceSecurityGroup ]
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow ping and ssh
        VpcId: "vpc-0610446fafca4df10"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance
      
Outputs:
  IID:
    Description: instance id
    Value: !Ref EC2Instance
    Export:
      Name: !Sub ${AWS::StackName}-instanceid
  PIP:
    Description: private ip for other CF templates
    Value: !GetAtt EC2Instance.PrivateIp
    Export:
      Name: !Sub ${AWS::StackName}-privateip
  PubIP:
    Description: public ip of the instance for other CF templates
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub ${AWS::StackName}-publicip
     