AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 6"

Resources:
  LaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: "ami-0149237d81c73e609"
      SecurityGroups: 
      - Ref: "InstanceSecurityGroup"
      InstanceType: "t2.medium"
      KeyName: "lab6-su-jmd"
  AutoScalingGroup:
    UpdatePolicy:
      AutoScalingRollingUpdate:
        # MinInstancesInService: '1'
        # MaxBatchSize: '1'
        AutoScalingReplacingUpdate:
          WillReplace: True
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: lab612-su-jmd
      MinSize: "1"
      MaxSize: "1"
      DesiredCapacity: "1"
      LaunchConfigurationName: !Ref LaunchConfig
      VPCZoneIdentifier:
        - "subnet-0017c4a5e72ed567f"
        - "subnet-06e941239860097ef"
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow ping and ssh
        VpcId: "vpc-0610446fafca4df10"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
