AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 5"

Resources:
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: lab512-su-jmd-winsvr
      LaunchTemplateData:
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
  Nix:
    Type: AWS::EC2::Instance
    Properties: 
      LaunchTemplate: 
        LaunchTemplateId: !Ref LaunchTemplate
        Version: "1"
      ImageId: "ami-0739f8cdb239fe9ae"
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Lab5.1.2
      SecurityGroupIngress:
        - CidrIp: 18.205.7.57/32
          Description: Allow SSH
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          Description: Allow All
          IpProtocol: icmp
          FromPort: -1
          ToPort: -1
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Nix

Outputs:
  PublicIP:
    Description: Nix PubIP
    Value: !Ref EIP
    Export:
      Name:  !Sub ${AWS::StackName}-pubip

      
#Microsoft Windows Server 2016 Base - ami-0088977e66ac3915d
#Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-0739f8cdb239fe9ae
