AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 5"

Resources:
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !Ref RoleCloudWatch
  RoleCloudWatch:
    Type: AWS::IAM::Role
    Properties: 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: lab512-su-jmd-nix
      LaunchTemplateData:
        KeyName: lab544-su-jmd
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
        InstanceType: t2.small
        IamInstanceProfile: 
          Name: !Ref InstanceProfile
        UserData: 
            Fn::Base64: !Sub | 
              #!/bin/bash -xe
              apt update
              apt -y install python-setuptools
              # mkdir aws-cfn-bootstrap-latest
              # curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xz -C aws-cfn-bootstrap-latest --strip-components 1
              # easy_install aws-cfn-bootstrap-latest
              # /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource Nix --region ${AWS::Region}
              # /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Nix --region ${AWS::Region}
              mkdir /mnt/xvdh
              mkfs -t ext4 /dev/xvdh
              echo "/dev/xvdh       /mnt/xvdh   ext4    defaults,nofail 0       2" >> /etc/fstab
              # mount the volume on current boot
              mount -a
              echo "foo" >> /mnt/xvdh/rabbit
  LaunchTemplateRestore:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: lab512-su-jmd-restore
      LaunchTemplateData:
        KeyName: lab544-su-jmd
        SecurityGroupIds:
          - !GetAtt SecurityGroup.GroupId
        InstanceType: t2.small
        IamInstanceProfile: 
          Name: !Ref InstanceProfile
        UserData: 
            Fn::Base64: !Sub | 
              #!/bin/bash -xe
              apt update
              apt -y install python-setuptools
              # mkdir aws-cfn-bootstrap-latest
              # curl https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz | tar xz -C aws-cfn-bootstrap-latest --strip-components 1
              # easy_install aws-cfn-bootstrap-latest
              # /usr/local/bin/cfn-init -v --stack ${AWS::StackName} --resource Nix --region ${AWS::Region}
              # /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource Nix --region ${AWS::Region}
              mkdir /mnt/xvdh
              echo "/dev/xvdh       /mnt/xvdh   ext4    defaults,nofail 0       2" >> /etc/fstab
              # mount the volume on current boot
              mount -a
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Lab5.1.2
      SecurityGroupIngress:
        - CidrIp: 54.197.44.171/32
          Description: Allow SSH
          IpProtocol: tcp
          FromPort: 22
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          Description: Allow All
          IpProtocol: icmp
          FromPort: -1
          ToPort: -1

Outputs:
  LaunchTemplateOut:
    Description: "launch template for import"
    Value: !Ref LaunchTemplate
    Export:
      Name:  !Sub ${AWS::StackName}-launchtemplate
  LaunchTemplateRestore:
    Description: "launch template for import for restore"
    Value: !Ref LaunchTemplateRestore
    Export:
      Name:  !Sub ${AWS::StackName}-launchtemplaterestore
  
      
#Microsoft Windows Server 2016 Base - ami-0088977e66ac3915d
#Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-0739f8cdb239fe9ae
