AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 5"

Resources:
  Nix:
    Type: AWS::EC2::Instance
    # BlockDeviceMappings:
    #   - DeviceName: /dev/sdc
    #     Ebs:
    #       SnapshotId: snap-xxxxxxxx
    #       VolumeSize: 4
    #       VolumeType: gp2
    #       Iops: 1000
    #       DeleteOnTermination: false
    Properties: 
      LaunchTemplate: 
        LaunchTemplateId: !ImportValue "jmd-020201221-001-launchtemplate"
        Version: "1"
      ImageId: "ami-0739f8cdb239fe9ae"
      AvailabilityZone: us-east-1a
  Volume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !GetAtt Nix.AvailabilityZone
      Size: 4
      VolumeType: gp2
  VolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/sdh
      InstanceId: !Ref Nix
      VolumeId: !Ref Volume
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Nix

  NixRestore:
    Type: AWS::EC2::Instance
    Properties: 
      BlockDeviceMappings:
      - DeviceName: /dev/sdc
        Ebs:
          SnapshotId: snap-0fb6e09b8240cd858
          VolumeSize: 4
          VolumeType: gp2
          Iops: 1000
          DeleteOnTermination: false
      LaunchTemplate: 
        LaunchTemplateId: !ImportValue "jmd-020201221-001-launchtemplate"
        Version: "1"
      ImageId: "ami-0739f8cdb239fe9ae"
      AvailabilityZone: us-east-1a
  EIPRestore:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref NixRestore


Outputs:
  PublicIP:
    Description: Nix PubIP
    Value: !Ref EIP
    Export:
      Name:  !Sub ${AWS::StackName}-pubip

      
#Microsoft Windows Server 2016 Base - ami-0088977e66ac3915d
#Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-0739f8cdb239fe9ae
