Parameters:
  ec2amiid: 
    Type: String
  r2ec2amiid: 
    Type: String
  instancetype:
    Type: String
  keypairname:
    Type: String
  r1cidr:
    Type: String
  r2cidr:
    Type: String
  r1vpcid:
    Type: String
  r2vpcid:
    Type: String
  r1peerid:
    Type: String

Resources:
  PeeringRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 10.10.0.0/16
      RouteTableId: !ImportValue "jmd-020201215-001-routetable"
      VpcPeeringConnectionId: !Ref r1peerid

