AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 4.2"

Parameters:
  ec2amiid: 
    Type: String
  r2ec2amiid: 
    Type: String
  instancetype:
    Type: String
  keypairname:
    Type: String
  r1cidr:
    Type: String
  r2cidr:
    Type: String
  r1vpcid:
    Type: String
  r2vpcid:
    Type: String
  r1peerid:
    Type: String
    
Resources:
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref r2ec2amiid
      # ImageId: !Ref LatestAmiId
      InstanceType: !Ref instancetype
      KeyName: 'lab413-su-jmdr2' 
      #!Ref keypairname
      SubnetId: !ImportValue "jmd-020201215-001-r2subnet"
      SecurityGroupIds: [ !Ref InstanceSecurityGroup ]
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow ping and ssh
        VpcId: !ImportValue "jmd-020201215-001-r2vpc"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
      
Outputs:
  IID:
    Description: instance id
    Value: !Ref EC2Instance
    Export:
      Name: !Sub ${AWS::StackName}-r2instance
  PIP:
    Description: private ip for other CF templates
    Value: !GetAtt EC2Instance.PrivateIp
    Export:
      Name: !Sub ${AWS::StackName}-privateip
  # Subnet:
  #   Description: subnet for other CF templates
  #   Value: !GetAtt EC2Instance.PublicIp
  #   Export:
  #     Name: !Sub ${AWS::StackName}-r2pubip
