AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 4"

# Properties:
#   Tags:
#     - Key: userCFlevel
#       Value: "jason.davis.labs"

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 172.0.0.0/16
      Tags:
        - Key: user
          Value: "jason.davis.labs"
        - Key: stelligent-u-lesson
          Value: "4.1"
        - Key: stelligent-u-lab
          Value: "4.1.1"

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 172.0.1.0/24
      Tags:
        - Key: user
          Value: "jason.davis.labs"
        - Key: stelligent-u-lesson
          Value: "4.1"
        - Key: stelligent-u-lab
          Value: "4.1.1"
          
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: user
          Value: "jason.davis.labs"
        - Key: stelligent-u-lesson
          Value: "4.1"
        - Key: stelligent-u-lab
          Value: "4.1.2"

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: user
          Value: "jason.davis.labs"
        - Key: stelligent-u-lesson
          Value: "4.1"
        - Key: stelligent-u-lab
          Value: "4.1.2"

  PublicRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId: !Ref PublicRouteTable
        DestinationCidrBlock: '0.0.0.0/0'
        GatewayId:
          Ref: InternetGateway

Outputs:
  VPC:
    Description: vpc for other CF templates
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}-vpc
  Subnet:
    Description: subnet for other CF templates
    Value: !Ref Subnet
    Export:
      Name: !Sub ${AWS::StackName}-subnet
