AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 4"

Parameters:
  # LatestAmiId:
  #   Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
  #   Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  ec2amiid: 
    Type: String
  instancetype:
    Type: String
  keypairname:
    Type: String

Resources:
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ec2amiid
      # ImageId: !Ref LatestAmiId
      InstanceType: !Ref instancetype
      KeyName: !Ref keypairname
      SubnetId: !ImportValue "jmd-020201215-001-subnet"
      
Outputs:
  IID:
    Description: instance id
    Value: !Ref EC2Instance
    Export:
      Name: !Sub ${AWS::StackName}-vpc
  Subnet:
    Description: subnet for other CF templates
    Value: !GetAtt EC2Instance.PrivateIp
    Export:
      Name: !Sub ${AWS::StackName}-subnet
