AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 4"

Parameters:
  ec2amiid: 
    Type: String
  r2ec2amiid: 
    Type: String
  instancetype:
    Type: String
  keypairname:
    Type: String
  r1cidr:
    Type: String
  r2cidr:
    Type: String
  r1vpcid:
    Type: String
  r2vpcid:
    Type: String
  r1peerid:
    Type: String

Resources:
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ec2amiid
      # ImageId: !Ref LatestAmiId
      InstanceType: !Ref instancetype
      KeyName: !Ref keypairname
      SubnetId: !ImportValue "jmd-020201215-001-subnet"
      SecurityGroupIds: [ !Ref InstanceSecurityGroup ]

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow ping and ssh
        VpcId: !ImportValue "jmd-020201215-001-vpc"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance

  NATEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ec2amiid
      InstanceType: !Ref instancetype
      KeyName: !Ref keypairname
      SubnetId: !ImportValue "jmd-020201215-001-natsubnet"
      SecurityGroupIds: [ !Ref InstanceSecurityGroup ]

Outputs:
  IID:
    Description: instance id
    Value: !Ref EC2Instance
    Export:
      Name: !Sub ${AWS::StackName}-instanceid
  PIP:
    Description: private ip for other CF templates
    Value: !GetAtt EC2Instance.PrivateIp
    Export:
      Name: !Sub ${AWS::StackName}-privateip
  PrIP:
    Description: public ip of the instance for other CF templates
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub ${AWS::StackName}-publicip
  NPIP:
    Description: private ip for other CF templates
    Value: !GetAtt NATEC2Instance.PrivateIp
    Export:
      Name: !Sub ${AWS::StackName}-natprivateip
