AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 4.2"

Parameters:
  ec2amiid: 
    Type: String
  r2ec2amiid: 
    Type: String
  instancetype:
    Type: String
  keypairname:
    Type: String
  r1cidr:
    Type: String
  r2cidr:
    Type: String
  r1vpcid:
    Type: String
  r2vpcid:
    Type: String
  r1peerid:
    Type: String
    
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref r2cidr
      Tags:
        - Key: user
          Value: "jason.davis.labs"
        - Key: stelligent-u-lesson
          Value: "4.2"
        - Key: stelligent-u-lab
          Value: "4.2.1"

  VPCPeeringConnection:
    Type: 'AWS::EC2::VPCPeeringConnection'
    Properties:
      VpcId: !Ref VPC
      PeerVpcId: !Ref r1vpcid
      PeerRegion: us-east-1

  PEERRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
  PeeringRoute:
    Type: 'AWS::EC2::Route'
    Properties:
      DestinationCidrBlock: 172.16.0.0/16
      RouteTableId: !Ref PEERRouteTable
      VpcPeeringConnectionId: !Ref VPCPeeringConnection

  PEERRouteTableSubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PEERRouteTable
      SubnetId: !Ref Subnet

  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.10.1.0/24
      Tags:
        - Key: user
          Value: "jason.davis.labs"
        - Key: stelligent-u-lesson
          Value: "4.2"
        - Key: stelligent-u-lab
          Value: "4.2.2"

  NetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: user
          Value: "jason.davis.labs"
        - Key: stelligent-u-lesson
          Value: "4.1"
        - Key: stelligent-u-lab
          Value: "4.2.2"

  SubnetNetworkAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref Subnet
      NetworkAclId: !Ref NetworkAcl

  InboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId: !Ref NetworkAcl
       RuleNumber: 100
       Protocol: 6
       RuleAction: allow
       CidrBlock: 172.16.0.0/16
       PortRange:
         From: 22
         To: 22
  InboundRuleicmp:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId: !Ref NetworkAcl
       RuleAction: allow
       CidrBlock: 172.16.0.0/16
       RuleNumber: 123
       Protocol: "1"
       Icmp:
         Code: "-1"
         Type: "-1"
       RuleAction: allow
  OutboundRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
       NetworkAclId: !Ref NetworkAcl
       RuleNumber: 200
       Protocol: -1
       Egress: true
       RuleAction: allow
       CidrBlock: 0.0.0.0/0

Outputs:
  VPC:
    Description: vpc for other CF templates
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}-r2vpc
  Subnet:
    Description: subnet for other CF templates
    Value: !Ref Subnet
    Export:
      Name: !Sub ${AWS::StackName}-r2subnet
