AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 4"

Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  ec2amiid: 
    Type: String
  instancetype:
    Type: String
  keypairname:
    Type: String

Resources:
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ec2amiid
      # ImageId: !Ref LatestAmiId
      InstanceType: !Ref instancetype
      KeyName: !Ref keypairname
      SubnetId: !ImportValue "jmd-020201215-001-subnet"
      SecurityGroupIds: [ !Ref InstanceSecurityGroup ]
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: Allow ping and ssh
        VpcId: !ImportValue "jmd-020201215-001-vpc"
        SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
  EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2Instance

  NATEIP:
    Type: AWS::EC2::EIP

  NAT:
     Type: AWS::EC2::NatGateway
     Properties:
        AllocationId: !GetAtt NATEIP.AllocationId
        SubnetId: !ImportValue "jmd-020201215-001-subnet"
        Tags:
          - Key: user
            Value: "jason.davis.labs"
          - Key: stelligent-u-lesson
            Value: "4.1"
          - Key: stelligent-u-lab
            Value: "4.1.7"

  # NATPublicRouteTable:
  #   Type: AWS::EC2::RouteTable
  #   Properties:
  #     VpcId: !ImportValue "jmd-020201215-001-vpc"
  #     Tags:
  #       - Key: user
  #         Value: "jason.davis.labs"
  #       - Key: stelligent-u-lesson
  #         Value: "4.1"
  #       - Key: stelligent-u-lab
  #         Value: "4.1.7"

  NATPublicRoute:
      Type: AWS::EC2::Route
      Properties:
        RouteTableId: !ImportValue "jmd-020201215-001-routetable"
        NatGatewayId: NAT
        DestinationCidrBlock: '172.0.2.0/24'
        NatGatewayId:
          Ref: NAT
          
  NATEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ec2amiid
      InstanceType: !Ref instancetype
      KeyName: !Ref keypairname
      SubnetId: !ImportValue "jmd-020201215-001-natsubnet"

Outputs:
  IID:
    Description: instance id
    Value: !Ref EC2Instance
    Export:
      Name: !Sub ${AWS::StackName}-instanceid
  PIP:
    Description: private ip for other CF templates
    Value: !GetAtt EC2Instance.PrivateIp
    Export:
      Name: !Sub ${AWS::StackName}-privateip
  PrIP:
    Description: public ip of the instance for other CF templates
    Value: !GetAtt EC2Instance.PublicIp
    Export:
      Name: !Sub ${AWS::StackName}-publicip
