AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 10"

Resources:
  LabKey:
    Type: AWS::KMS::Key
    Properties:
      Description: initial key
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Sub "${AWS::StackName}-key-1"
        Statement:
        - Sid: Enable IAM User Permissions for root
          Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
          Action: kms:*
          Resource: '*'
        - Sid: Allow administration of the key
          Effect: Allow
          Principal:
                     # arn:aws:iam::324320755747     :user/jason.davis.labs
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/jason.davis.labs"
          Action:
          - kms:Create*
          - kms:Describe*
          - kms:Enable*
          - kms:List*
          - kms:Put*
          - kms:Update*
          - kms:Revoke*
          - kms:Disable*
          - kms:Get*
          - kms:Delete*
          - kms:ScheduleKeyDeletion
          - kms:CancelKeyDeletion
          Resource: '*'
        - Sid: Allow use of the key
          Effect: Allow
          Principal:
            AWS: !Sub "arn:aws:iam::${AWS::AccountId}:user/jason.davis.labs"
          Action:
          - kms:DescribeKey
          - kms:Encrypt
          - kms:Decrypt
          - kms:ReEncrypt*
          - kms:GenerateDataKey
          - kms:GenerateDataKeyWithoutPlaintext
          Resource: '*'

  LabAlias:          
    Type: AWS::KMS::Alias
    Properties: 
      AliasName: !Sub "alias/${AWS::StackName}-lab1012"
      TargetKeyId: !Ref LabKey
