AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Lab121user:
    Type: 'AWS::IAM::User'
    Properties: 
      UserName: '{{resolve:ssm:jmd-lab12r-username:1}}'
      #'AWS::SSM::Parameter::Value<jmd-lab12r-username>'
  Lab121managedpolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: jmd-lab121-s3mp
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 
              - 's3:GetObject'
              - 's3:ListAllMyBuckets'
              - 's3:ListBucket'
            Resource: '*'
      Users: 
        - !Ref Lab121user
Outputs:
  Lab122:
    Description: arn policy output
    Value: !Ref Lab121managedpolicy
    Export:
      Name: Lab121managedpolicy-arn