AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  LabBucketName: 
    Type: String
Conditions: 
  Prefered_Region: !Equals ["us-east-1", !Ref 'AWS::Region']
Resources:
  Lab111:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !If [Prefered_Region, !Join [ "-", [ !Ref 'AWS::AccountId', !Ref 'LabBucketName' ] ], !Ref 'LabBucketName']
