AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Lab123user:
    Type: 'AWS::IAM::User'
    Properties: 
      UserName: jmdmp-lab123
      ManagedPolicyArns:
        - Fn::ImportValue: "Lab121managedpolicy-arn"