AWSTemplateFormatVersion: "2010-09-09"

Resources:

  LogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub "${AWS::StackName}"
      RetentionInDays: 7
      
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "stelligent-u-922-jason.davis.labs"
      Tags:
        - Key: user
          Value: "jason.davis.labs"
        - Key: stelligent-u-lesson
          Value: "9"
        - Key: stelligent-u-lab
          Value: "9.2.2"
          
  TrailOfLogs:
    Type: AWS::CloudTrail::Trail
    Properties: 
      CloudWatchLogsLogGroupArn: !GetAtt LogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt RoleCloudWatch.Arn
      IsLogging: True
      S3BucketName: !Ref Bucket
      TrailName: String

  EventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "s3 put something"
      Name: "lab922-s3put"
      EventPattern:
        source:
          - aws.s3
        detail:
          - eventSource: "s3.amazonaws.com"
          - eventName: "PutObject"
      State: "ENABLED"
      Targets: 
        - Arn: !Ref LambdaFunction
          Id: "lambda-to-dynamoDB"

  RoleCloudWatch:
    Type: AWS::IAM::Role
    Properties: 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "cloudtrail.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
              
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: "stelligent-u-922-jason.davis.labs"
      PolicyDocument:
        Statement:
          - Sid: "CloudTrail020201229"
            Effect: "Allow"
            Principal: '*'
            # Principal: 
            # - Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: "arn:aws:s3:::stelligent-u-922-jason.davis.labs"
          - Sid: "CloudTrailWrite020201224"
            Effect: "Allow"
            Principal: '*'
            Action: "s3:PutObject"
            Resource: "arn:aws:s3:::stelligent-u-922-jason.davis.labs/*"