AWSTemplateFormatVersion: "2010-09-09"

Resources:

  LogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: !Sub "${AWS::StackName}"
      RetentionInDays: 7
      
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "stelligent-u-922-jason.davis.labs"
      Tags:
        - Key: user
          Value: "jason.davis.labs"
        - Key: stelligent-u-lesson
          Value: "9"
        - Key: stelligent-u-lab
          Value: "9.2.2"

  BucketStack:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::StackName}"
      Tags:
        - Key: user
          Value: "jason.davis.labs"
        - Key: stelligent-u-lesson
          Value: "9"
        - Key: stelligent-u-lab
          Value: "9.2.2"
          
  TrailOfLogs:
    Type: AWS::CloudTrail::Trail
    Properties: 
      CloudWatchLogsLogGroupArn: !GetAtt LogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt RoleCloudWatch.Arn
      IsLogging: True
      S3BucketName: !Ref Bucket
      TrailName: String

  EventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "s3 put something"
      Name: "lab922-s3put"
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - 'AWS API Call via CloudTrail'
        detail:
          eventSource:
            - s3.amazonaws.com
          eventName:
            # - CopyObject
            - PutObject
            # - CompleteMultipartUpload
          requestParameters:
            bucketName:
              - !Ref BucketStack
            # key:
            #   - !Ref SourceObjectKey
      State: "ENABLED"
      Targets: 
        - Arn: !Ref LambdaFunction
          Id: "lambda-to-dynamoDB"

  RoleCloudWatch:
    Type: AWS::IAM::Role
    Properties: 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "cloudtrail.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
              
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: "stelligent-u-922-jason.davis.labs"
      PolicyDocument:
        Statement:
          - Sid: "CloudTrail020201229"
            Effect: "Allow"
            Principal: '*'
            Action: "s3:GetBucketAcl"
            Resource: "arn:aws:s3:::stelligent-u-922-jason.davis.labs"
          - Sid: "CloudTrailWrite020201224"
            Effect: "Allow"
            Principal: '*'
            Action: "s3:PutObject"
            Resource: "arn:aws:s3:::stelligent-u-922-jason.davis.labs/*"

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "lab922-example-table"
      AttributeDefinitions:
      - AttributeName: "bucketName"
        AttributeType: "S"
      - AttributeName: "key"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "bucketName"
        KeyType: HASH
      - AttributeName: "key"
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies: 
        - 
          PolicyName: "LambdaToDTable"
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Sid: "LambdaToDTableAllowAll"
                Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*"
                  
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}"
      Role: !GetAtt LambdaRole.Arn
      Runtime: python3.7
      Handler: index.lab922
      Timeout: 900
      Code:
        ZipFile: |
          import json
          from pprint import pprint
          import boto3
          dynamodb = boto3.resource('dynamodb', region_name='us-east-1')
          table = dynamodb.Table('lab922-example-table')
          def lab922(event, context):
            record = {
              'bucketName': int(event['bucketName']),
              'key': event['key']
            }
            response=table.put_item(Item=record)
            return response
