AWSTemplateFormatVersion: "2010-09-09"

Resources:

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "stelligent-u-922-jason.davis.labs-transfer"
      Tags:
        - Key: user
          Value: "jason.davis.labs"
        - Key: stelligent-u-lesson
          Value: "9"
        - Key: stelligent-u-lab
          Value: "9.2.2"

  BucketPolicy:
    DependsOn: Bucket
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: "stelligent-u-922-jason.davis.labs-transfer"
      PolicyDocument:
        Statement:
          - Sid: "CloudTrail020201229"
            Effect: "Allow"
            Principal: '*'
            Action: "s3:GetBucketAcl"
            Resource: "arn:aws:s3:::stelligent-u-922-jason.davis.labs-transfer"
          - Sid: "CloudTrailWrite020201224"
            Effect: "Allow"
            Principal: '*'
            Action: "s3:PutObject"
            Resource: "arn:aws:s3:::stelligent-u-922-jason.davis.labs-transfer/*"