AWSTemplateFormatVersion: 2010-09-09
Description: "lab 2.2.4"

Resources:
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: "stelligent-u-224-jason.davis.labs"
      PolicyDocument:
        Statement:
          - Sid: Allow
            Effect: Allow
            Action: s3:*
            Principal: 
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:user/jason.davis.labs
            Resource:
              - !Sub arn:aws:s3:::stelligent-u-224-jason.davis.labs/*
          - Sid: PublicRead
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::stelligent-u-224-jason.davis.labs/tosync/*
          - Sid: Private
            Effect: Deny
            Action: s3:GetObject
            NotPrincipal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:user/jason.davis.labs
            Resource: !Sub arn:aws:s3:::stelligent-u-224-jason.davis.labs/tosync/private.txt
