AWSTemplateFormatVersion: 2010-09-09
Description: "lab 12.2.2"

Parameters:
  GitHubToken:
    Type: String
    Description: GitHub OAuth Token
    NoEcho: True
  ChangeSetPipeline:
    Type: String
    Description: stack name for the pipeline to manage
    Default: "jmd-DB1-001"
  PipeTableName:
    Type: String
    Description: table name to pass into code pipeline
    Default: "lab1222-defaultpipeline"

Resources:
  PipelineStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "stelligent-u-lab1222-pipelinestate-jason.davis.labs"

  PipelineExeRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - codepipeline.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: codepipeline-service
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action:
                - 'cloudformation:CreateStack'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:UpdateStack'
                - 'cloudformation:SetStackPolicy'
                - 'logs:*'
              Effect: Allow
              Resource:
                - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ChangeSetPipeline}/*
            - Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:PutObject
              Resource: !Sub 'arn:aws:s3:::${PipelineStateBucket}/*'
              Effect: Allow
            - Action:
                - 'iam:PassRole'
              Effect: Allow
              Resource:
                - !GetAtt MakeDBRole.Arn            
            - Action:
                - s3:GetBucketVersioning
              Resource: !Sub 'arn:aws:s3:::${PipelineStateBucket}'
              Effect: Allow

  MakeDBRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: 
                - cloudformation.amazonaws.com
      Path: /
      Policies:
      - PolicyName: cloudformation-service
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action:
                - 'dynamodb:CreateTable'
                - 'dynamodb:DescribeTable'
                - 'dynamodb:Delete*'
                - 'dynamodb:Update*'
                - 'dynamodb:PutItem'
              Resource: 
                - !Sub 'arn:aws:dynamodb:us-east-1:324320755747:table/${PipeTableName}'
              Effect: Allow
            - Action:
                - s3:ListAllMyBuckets
                - s3:CreateBucket
                - s3:ListBucket
                - s3:HeadBucket
              Resource: '*'
              Effect: Allow
            - Action:
                - 'iam:GetRole'
                - 'iam:CreateRole'
                - 'iam:PutRolePolicy'
                - 'iam:DeleteRolePolicy'
                - 'iam:GetRolePolicy'
              Effect: Allow
              Resource:
                - !Sub 'arn:aws:iam::324320755747:role/${ChangeSetPipeline}'

  AppPipeline: 
    Type: AWS::CodePipeline::Pipeline 
    Properties: 
      RoleArn: !GetAtt PipelineExeRole.Arn
      Stages: 
        - 
          Name: Lab1222-Source
          Actions: 
            - Name: SourceAction
              ActionTypeId: 
                Category: Source 
                Owner: ThirdParty
                Version: 1 
                Provider: GitHub
              OutputArtifacts: 
                - Name: BucketTemplate 
              Configuration: 
                  Owner: stelligent
                  Repo: su-jmd-020201208
                  PollForSourceChanges: true
                  Branch: DeployPipeline
                  OAuthToken: !Ref GitHubToken
              RunOrder: 1 
        - 
          Name: Lab1222-Deploy 
          Actions: 
            - Name: DeployAction 
              InputArtifacts: 
                - Name: BucketTemplate
              ActionTypeId:     
                Category: Deploy 
                Owner: AWS 
                Version: '1' 
                Provider: CloudFormation
              Configuration: 
                ActionMode: REPLACE_ON_FAILURE
                Capabilities:  CAPABILITY_NAMED_IAM
                StackName: !Ref ChangeSetPipeline
                RoleArn: !GetAtt MakeDBRole.Arn
                TemplatePath: "BucketTemplate::12-codepipeline/lab1221.yml"
                ParameterOverrides: !Sub |
                  {
                    "PipeEnvTableName": "${PipeTableName}"
                  }
              RunOrder: 2 
      ArtifactStore: 
        Type: S3 
        Location: !Ref PipelineStateBucket
