AWSTemplateFormatVersion: 2010-09-09
Description: "lab 12.2.2"

Parameters:
  GitHubToken:
    Type: String
    Description: GitHub OAuth Token
    NoEcho: True
  ChangeSetPipeline:
    Type: String
    Description: stack name for the pipeline to manage
    Default: "jmd-DB1-001"
  PipeTableName:
    Type: String
    Description: table name to pass into code pipeline
    Default: "lab1222-CS001"

Resources:
  PipelineStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "stelligent-u-lab1222-pipelinestate-jason.davis.labs"

  PipelineExeRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - codepipeline.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: codepipeline-service
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action:
                - 'codebuild:BatchGetBuilds'
                - 'codebuild:StartBuild'
              Resource: 
                - !Sub arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/lab1222*
              Effect: Allow
            - Action:
                - 'cloudformation:CreateStack'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:UpdateStack'
                - 'cloudformation:SetStackPolicy'
                - 'cloudformation:CreateChangeSet'
                - 'cloudformation:ExecuteChangeSet'
                - 'logs:*'
              Effect: Allow
              Resource:
                - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/${ChangeSetPipeline}/*
            - Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:PutObject
              Resource: !Sub 'arn:aws:s3:::${PipelineStateBucket}/*'
              Effect: Allow
            - Action:
                - 'iam:PassRole'
              Effect: Allow
              Resource:
                - !GetAtt MakeDBRole.Arn            
            - Action:
                - s3:GetBucketVersioning
              Resource: !Sub 'arn:aws:s3:::${PipelineStateBucket}'
              Effect: Allow

  MakeDBRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: 
                - cloudformation.amazonaws.com
      Path: /
      Policies:
      - PolicyName: cloudformation-service
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action:
                - 'dynamodb:CreateTable'
                - 'dynamodb:DescribeTable'
                - 'dynamodb:Delete*'
                - 'dynamodb:Update*'
                - 'dynamodb:PutItem'
              Resource: 
                - !Sub 'arn:aws:dynamodb:us-east-1:324320755747:table/${PipeTableName}'
              Effect: Allow
            - Action:
                - s3:ListAllMyBuckets
                - s3:CreateBucket
                - s3:ListBucket
                - s3:HeadBucket
              Resource: '*'
              Effect: Allow
            - Action:
                - 'iam:GetRole'
                - 'iam:CreateRole'
                - 'iam:PutRolePolicy'
                - 'iam:DeleteRolePolicy'
                - 'iam:GetRolePolicy'
              Effect: Allow
              Resource:
                - !Sub 'arn:aws:iam::324320755747:role/${ChangeSetPipeline}'

  AppPipeline: 
    Type: AWS::CodePipeline::Pipeline 
    Properties: 
      RoleArn: !GetAtt PipelineExeRole.Arn
      Stages: 
        - 
          Name: Lab1222-Source
          Actions: 
            - Name: SourceAction
              ActionTypeId: 
                Category: Source 
                Owner: ThirdParty
                Version: 1 
                Provider: GitHub
              OutputArtifacts: 
                - Name: ScriptsNSuch 
              Configuration: 
                  Owner: stelligent
                  Repo: su-jmd-020201208
                  PollForSourceChanges: true
                  Branch: DeployPipeline
                  OAuthToken: !Ref GitHubToken
              RunOrder: 1 
        - 
          Name: Lab1222-CU-Stack 
          Actions:
            -
              Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: ScriptsNSuch
              Configuration:
                ProjectName: !Ref CodeBuildCUStack
              OutputArtifacts:
                - Name: CUStack
              RunOrder: 2
        - 
          Name: Lab1222-Approval
          Actions:
            -
              Name: ApprovalAction
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              # InputArtifacts:
              #   - Name: ScriptsNSuch
              Configuration:
                ProjectName: !Ref CodeBuildExe
              # OutputArtifacts:
              #   - Name: ExeStack
              RunOrder: 3
        - 
          Name: Lab1222-Exe
          Actions:
            -
              Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: ScriptsNSuch
              Configuration:
                ProjectName: !Ref CodeBuildExe
              OutputArtifacts:
                - Name: ExeStack
              RunOrder: 4
      ArtifactStore: 
        Type: S3 
        Location: !Ref PipelineStateBucket

  CodeBuildCUStack:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: S3
        Location: !Sub "${PipelineStateBucket}/prefix"
      Description: "Create or Update changeset and stack"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/eb-python-3.4-amazonlinux-64:2.3.2
      Name: 'lab1222-CUStack'
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: '12-codepipeline/lab1222-linuxcontainer-CU.yml'

  CodeBuildExe:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Cache:
        Type: S3
        Location: !Sub "${PipelineStateBucket}/prefix"
      Description: "Execute the ChangeSet"
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/eb-python-3.4-amazonlinux-64:2.3.2
      Name: 'lab1222-Exe'
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE
        BuildSpec: '12-codepipeline/lab1222-linuxcontainer-Exe.yml'

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
              - codebuild.amazonaws.com
      Path: /
      Policies:
        - PolicyName: allow-code-build
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                  - logs:*
                  - cloudformation:DescribeStacks
                  - cloudformation:ValidateTemplate
                  - cloudformation:CreateChangeSet
                  - cloudformation:ExecuteChangeSet
                  - iam:PassRole
                Effect: Allow
                Resource: "*"
              - Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${PipelineStateBucket}/*"
                Effect: Allow
              - Action:
                  - iam:GetRole
                  - iam:CreateRole
                  - iam:DeleteRole
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:GetRolePolicy
                Effect: Allow
                Resource:
                  - arn:aws:iam::324320755747:role/jmd-DB1-001
              - Action:
                  - dynamodb:CreateTable
                  - dynamodb:DescribeTable
                  - dynamodb:Delete*
                  - dynamodb:Update*
                  - dynamodb:PutItem
                Effect: Allow
                Resource: 
                  - !Sub 'arn:aws:dynamodb:us-east-1:324320755747:table/${PipeTableName}'
