AWSTemplateFormatVersion: 2010-09-09
Description: "lab 12.2.1 application w dynamoDB"

Parameters:
  DBField1:
    Type: String
    Description: database field as a param
    Default: field1
  DBField2:
    Type: String
    Description: database field as a param
    Default: field2
  DBField3:
    Type: String
    Description: database field as a param
    Default: field3


Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "lab1221-bicycle"
      AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "N"
      - AttributeName: !Sub "${DBField1}"
        AttributeType: "S"
      - AttributeName: !Sub "${DBField2}"
        AttributeType: "S"
      - AttributeName: !Sub "${DBField3}"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "id"
        KeyType: HASH
      - AttributeName: !Sub "${DBField1}"
        KeyType: RANGE
      - AttributeName: !Sub "${DBField2}"
        KeyType: RANGE
      - AttributeName: !Sub "${DBField3}"
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        
  appRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies: 
        - 
          PolicyName: "LambdaToDTable"
          PolicyDocument: 
            Version: '2012-10-17'
            Statement:
              - Sid: "LambdaToDTableAllowAll"
                Effect: Allow
                Action:
                  - dynamodb:*
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/*"
