AWSTemplateFormatVersion: 2010-09-09
Description: "lab 12.1.1"

Parameters:
  GitHubToken:
    Type: String
    Description: GitHub OAuth Token
    NoEcho: True
  BucketNameParameter:
    Type: String
    Description: S3 bucket name to be passed in cnf
    Default: su-jmd-020210105-lab1211
    
Resources:
  PipelineStateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "stelligent-u-1211-pipelinestate-jason.davis.labs"

  PipelineExeRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
              - codepipeline.amazonaws.com
          Action:
            - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: codepipeline-service
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Action:
                - 'cloudformation:CreateStack'
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DeleteStack'
                - 'cloudformation:UpdateStack'
                - 'cloudformation:SetStackPolicy'
                - 'logs:*'
              Effect: Allow
              Resource:
                - !Sub arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:stack/jmd-020210105-PIPELINE/*
            - Action:
                - 'iam:PassRole'
              Effect: Allow
              Resource:
                - !GetAtt MakeBucketRole.Arn            
            - 
              Action:
                - s3:GetObject
                - s3:GetObjectVersion
                - s3:PutObject
              Resource: !Sub 'arn:aws:s3:::${PipelineStateBucket}/*'
              Effect: Allow
            - 
              Action:
                - s3:GetBucketVersioning
              Resource: !Sub 'arn:aws:s3:::${PipelineStateBucket}'
              Effect: Allow

  MakeBucketRole:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: 
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service: 
                - cloudformation.amazonaws.com
      Path: /
      Policies:
      - PolicyName: cloudformation-service
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - 
              Action:
                - 's3:*'
              Resource: 
                - !Sub 'arn:aws:s3:::${BucketNameParameter}'
                - !Sub 'arn:aws:s3:::${BucketNameParameter}/*'
              Effect: Allow
            - 
              Action:
                - s3:ListAllMyBuckets
                - s3:CreateBucket
                - s3:ListBucket
                - s3:HeadBucket
              Resource: '*'
              Effect: Allow

  AppPipeline: 
    Type: AWS::CodePipeline::Pipeline 
    Properties: 
      RoleArn: !GetAtt PipelineExeRole.Arn
      Stages: 
        - 
          Name: Lab1211-Source
          Actions: 
            - Name: SourceAction
              ActionTypeId: 
                Category: Source 
                Owner: ThirdParty
                Version: 1 
                Provider: GitHub
              OutputArtifacts: 
                - Name: BucketTemplate 
              Configuration: 
                  Owner: stelligent
                  Repo: su-jmd-020201208
                  PollForSourceChanges: true
                  Branch: DeployPipeline
                  OAuthToken: !Ref GitHubToken
              RunOrder: 1 
        - 
          Name: Lab1211-Deploy 
          Actions: 
            - Name: DeployAction 
              InputArtifacts: 
                - Name: BucketTemplate
              ActionTypeId: 
                Category: Deploy 
                Owner: AWS 
                Version: '1' 
                Provider: CloudFormation
              Configuration: 
                ActionMode: REPLACE_ON_FAILURE
                StackName: jmd-020210105-PIPELINE
                RoleArn: !GetAtt MakeBucketRole.Arn
                TemplatePath: "BucketTemplate::12-codepipeline/bucket.yaml"
                ParameterOverrides: '{"BucketNameParameter": "${BucketNameParameter}"}'
              RunOrder: 2 
      ArtifactStore: 
        Type: S3 
        Location: !Ref PipelineStateBucket
