AWSTemplateFormatVersion: "2010-09-09"

Resources:

  LogGroup: 
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: "su-jmd-020201224"
      RetentionInDays: 7

  TrailLogs:
    Type: AWS::CloudTrail::Trail
    Properties: 
      CloudWatchLogsLogGroupArn: !GetAtt LogGroup.Arn
      CloudWatchLogsRoleArn: !GetAtt RoleCloudWatch.Arn
      # EnableLogFileValidation: Boolean
      # EventSelectors: 
      #   - EventSelector
      # IncludeGlobalServiceEvents: Boolean
      IsLogging: True
      # IsMultiRegionTrail: Boolean
      # KMSKeyId: String
      S3BucketName: !Ref Bucket
      # S3KeyPrefix: String
      # SnsTopicName: String
      # Tags: 
      #   - Tag
      TrailName: String

  RoleCloudWatch:
    Type: AWS::IAM::Role
    Properties: 
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              Service: 
                - "cloudtrail.amazonaws.com"
            Action: 
              - "sts:AssumeRole"

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "stelligent-u-821-jason.davis.labs"
      LifecycleConfiguration:
              Rules:
                - Id: LabLifecycle
                  AbortIncompleteMultipartUpload:
                    DaysAfterInitiation: 3
                  NoncurrentVersionExpirationInDays: 14
                  Status: Enabled
                  Transitions:
                    - StorageClass: STANDARD_IA
                      TransitionInDays: 30

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: "stelligent-u-821-jason.davis.labs"
      PolicyDocument:
        Statement:
          - Sid: "AWSCloudTrailAclCheck020201224"
            Effect: "Allow"
            Principal: '*'
            # Principal: 
            # - Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: "arn:aws:s3:::stelligent-u-821-jason.davis.labs"
          - Sid: "AWSCloudTrailAclWrite020201224"
            Effect: "Allow"
            Principal: '*'
            Action: "s3:PutObject"
            Resource: "arn:aws:s3:::stelligent-u-821-jason.davis.labs/*"
#            "Condition": {"StringEquals": {"s3:x-amz-acl": "bucket-owner-full-control"}}
