AWSTemplateFormatVersion: 2010-09-09
Description:  "lesson 4"

Parameters:
   LatestAmiId:
     Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
     Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'

Resources:
  EC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref LatestAmiId
      InstanceType: "t2.small"
    #   KeyName: !Ref keypairname
    #   SubnetId: !ImportValue "jmd-020201215-001-subnet"

