Description: "cloud9 ide for Stelligent U 00- module"

Resources:
  IDE: 
    Type: AWS::Cloud9::EnvironmentEC2
    Properties: 
      AutomaticStopTimeMinutes: 30
      ConnectionType: CONNECT_SSH
      Description: Jason's Stelligent U dev cloud9 ide
      InstanceType: t2.small
      Name: Stelli-U-jmd-env
      Tags: 
        - Key: "owner"
          Value: "Jason Davis"
