AWSTemplateFormatVersion: 2010-09-09
Description: "lab 3.2.1 trust policy"

Resources:
  LabRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              AWS: 
                - !Sub "arn:aws:iam::${AWS::AccountId}:user/jason.davis.labs"
            Action: 
              - "sts:AssumeRole"
      Policies:
        - PolicyName: su-331ab
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: afull
                Effect: Allow
                Action: 
                  - s3:List*
                  - s3:Get*
                  - s3:Put*
                Resource: "arn:aws:s3:::su-331a-jason.davis.labs/*"     
      RoleName: "su-jdlabs-331"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'


  BucketA:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "su-331a-jason.davis.labs"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
              Rules:
                - Id: LabLifecycle
                  AbortIncompleteMultipartUpload:
                    DaysAfterInitiation: 3
                  NoncurrentVersionExpirationInDays: 14
                  Status: Enabled
                  Transitions:
                    - StorageClass: STANDARD_IA
                      TransitionInDays: 30

  BucketB:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "su-331b-jason.davis.labs"
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
              Rules:
                - Id: LabLifecycle
                  AbortIncompleteMultipartUpload:
                    DaysAfterInitiation: 3
                  NoncurrentVersionExpirationInDays: 14
                  Status: Enabled
                  Transitions:
                    - StorageClass: STANDARD_IA
                      TransitionInDays: 30
