AWSTemplateFormatVersion: 2010-09-09
Description: "lab 3.1.1 iam role"

Resources:
  LabRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      RoleName: "su-jdlabs-311"
      ManagedPolicyArns:
        - !Ref LabPolicy

  LabRole313:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "ec2.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      RoleName: "su-jdlabs-313"
      ManagedPolicyArns:
        - !Ref LabPolicy
      
  LabPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties: 
      Description: "added role 315"
      # ManagedPolicyName: su-jdlabs-mp-312
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
            - iam:Get*
            - iam:List*
            - iam:SimulatePrincipalPolicy
            - ec2:DescribeImages
            - ec2:RunInstances
            - ec2:DescribeSecurityGroups
            Resource: "arn:aws:iam::*"
      # Roles:
      #   - !Ref LabRole
      #   - !Ref LabRole313

Outputs:
  LabRole:
    Description: arn role output
    # Value: !Ref Fn::GetAtt: [ "LabRole", "Arn" ]
    Value: !GetAtt LabRole.Arn
    Export:
      Name: LabRole-Arn
  LabRole313:
    Description: arn role313 output
    Value: !GetAtt LabRole313.Arn
    Export:
      Name: LabRole313-Arn
