AWSTemplateFormatVersion: 2010-09-09
Description: "lab 3.2.1 trust policy"

Resources:
  LabRole:
    Type: "AWS::IAM::Role"
    Properties: 
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Principal: 
              AWS: 
                - !Sub "arn:aws:iam::${AWS::AccountId}:user/jason.davis.labs"
            Action: 
              - "sts:AssumeRole"
      RoleName: "su-jdlabs-321"
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
