AWSTemplateFormatVersion: '2010-09-09'
# Parameters:
  # chase: 
  #   Type: 'AWS::SSM::Parameters::Value<String>'
    # Default: /env/rabbit
  # chasecar: 
  #   Type: String
  #   Default: '{{resolve::ssm:potato:1}}'

Parameters:
  BucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: 'potato'
    Description: Bucket Name  from SSM that host website
  BucketName2:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/env/rabbit'
    Description: Bucket Name  from SSM that host website
Resources:
  makebucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join [ "-", [ !Ref 'AWS::Region', !Ref 'AWS::AccountId', !Ref BucketName ] ]
  makebucket2:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join [ "-", [ !Ref 'AWS::Region', !Ref 'AWS::AccountId', !Ref BucketName2 ] ]
  document: 
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: '2.2'
        description: 'Run a script on Linux instances.'
        parameters:
          commands:
            type: String
            description: "(Required) The commands to run or the path to an existing script
          on the instance."
            default: 'echo Hello World'
        mainSteps:
        - action: aws:runShellScript
          name: runCommands
          inputs:
            timeoutSeconds: '60'
            runCommand:
            - "{{ aws --version }}"
      DocumentType: Command
      Name: 'CFN_2.2_command_example'