AWSTemplateFormatVersion: '2010-09-09'
# Parameters:
  # chase: 
  #   Type: 'AWS::SSM::Parameters::Value<String>'
    # Default: /env/rabbit
  # chasecar: 
  #   Type: String
  #   Default: '{{resolve::ssm:potato:1}}'

Parameters:
  BucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: 'potato'
    Description: Bucket Name  from SSM that host website
  BucketName2:
    Type: AWS::SSM::Parameter::Value<String>
    Default: '/env/rabbit'
    Description: Bucket Name  from SSM that host website
Resources:
  makebucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join [ "-", [ !Ref 'AWS::Region', !Ref 'AWS::AccountId', !Ref BucketName ] ]
  makebucket2:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join [ "-", [ !Ref 'AWS::Region', !Ref 'AWS::AccountId', !Ref BucketName2 ] ]
