AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  chase: 
    Type: 'AWS::SSM::Parameters::Value</env/rabbit>'
#    Default: /env/rabbit
Resources:
  makebucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join [ "-", [ !Ref 'AWS::Region', !Ref 'AWS::AccountId', !Ref 'chase' ] ]
