AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  EngName: 
    Type: String
  EngTeam: 
    Type: String
  EngTimeZone: 
    Type: String
  EngState: 
    Type: String
  EngStartDate: 
    Type: String

Resources:
  ParmName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /jason.davis.labs/stelligent-u/lab11/name
      Type: String
      Value: !Ref EngName 
      AllowedPattern: "^[a-zA-Z]{1,50}$"
  ParmTeam:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /jason.davis.labs/stelligent-u/lab11/team
      Type: String
      Value: !Ref EngTeam
  ParmTimeZone:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /jason.davis.labs/stelligent-u/lab11/timezone
      Type: String
      Value: !Ref EngTimeZone
  ParmState:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /jason.davis.labs/stelligent-u/lab11/state
      Type: String
      Value: !Ref EngState
  ParmStartDate:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /jason.davis.labs/stelligent-u/lab11/start-date
      Type: String
      Value: !Ref EngStartDate
