---
Description: Reachability check in CNF for Stelligent SiC 020210115
AWSTemplateFormatVersion: 2010-09-09

Resources:
  NIPCheckInstanceAB:
    Type: AWS::EC2::NetworkInsightsPath
    Properties: 
      Destination: !ImportValue jmd-SiC-020210110-001-InstanceB
      # DestinationIp: String
      # DestinationPort: Integer
      Protocol: tcp
      Source: !ImportValue jmd-SiC-020210110-001-InstanceA
      # SourceIp: String
      Tags:
        - Key: Description
          Value: "check that A can connect to B"          
          
  NIPCheckInstanceAC:
    Type: AWS::EC2::NetworkInsightsPath
    Properties: 
      Destination: !ImportValue jmd-SiC-020210110-001-InstanceC
      # DestinationIp: String
      # DestinationPort: Integer
      Protocol: tcp
      Source: !ImportValue jmd-SiC-020210110-001-InstanceA
      # SourceIp: String
      Tags:
        - Key: Description
          Value: "check that A can not connect to C"          
